### ISSUE TITLE
Variable names

### ISSUE THREAD

**Issue by merijnslagter** [GreatEmerald/RGIC1601#27]
While creating a table of all attribute names, I would like to discuss the names created in the modules.

I like the current names, but would like to suggest a tiny changes and additions. Please feel free to comment. The proposed variable names will be listed below:

**GetComponent()** :
current variable name(s): 'dataReductionMethod' and 'Aggregation' 
suggested variable name(s): 'data_reduction_method' and 'aggregation_factor'
https://github.com/GreatEmerald/RGIC1601/blob/master/backend/src/modules/GetComponent.r#L70

**ClassifyToZones()**
current variable name(s): 'clusterMethod'
suggested variable name(s): 'cluster_method'
https://github.com/GreatEmerald/RGIC1601/blob/master/backend/src/modules/ClassifyToZones.r#L82

**HomogeniseRaster()**
current variable name(s): 'windowType', 'filterType'
suggested variable name(s): 'window_type', 'filter_type'
other comments: would it be a good idea to have a default window_type?
https://github.com/GreatEmerald/RGIC1601/blob/master/backend/src/modules/HomogeniseRaster.r#L66

**GetSamplingLocations()**
current variable name(s): 'sample_num', 'method'
suggested variable name(s): 'number_of_samples', 'sampling_method'
https://github.com/GreatEmerald/RGIC1601/blob/master/backend/src/modules/GetSamplingLocations.R#L96

**Comment by yyixiong** [comment]
solved

**Comment by merijnslagter** [comment]
**Homogenizeraster()**
It might be nice to add the minimum zone size to the metadata here!

https://github.com/GreatEmerald/RGIC1601/blob/master/backend/src/modules/HomogeniseRaster.r#L66

**Comment by grathee** [comment]
it is difficult to calculate exact minimum area of the smallest zone with the raster.. However, i have included in metadata information about the window size, and type, so area will be pi*r2 for circular and len2 for rectangle.

**Comment by merijnslagter** [comment]
Nice that you included that! I was just wondering, is the argument min_ar the minimum zone size? Then you could simply add that to metadata right? I was wondering what exactly does window size mean, why would the user want to know?

**Comment by grathee** [comment]
Moving window decides how many cells will the function consider around the central cell to assign a new value depending on the surroundings. 
So, min area does have implications on the moving window as moving window is calculated as the radius of the min_area for circular moving window, for square it is the length.  Hence the information is recorded in metadata.
At the moment, i am using radius and length divided by two, to define the size of moving window because otherwise the moving window becomes to big and we loose information about the management zone 2, the long strip running across the field. For more information read about focal and focal weight function online.
For any doubt just ask. :)
